[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy==1.12.1; python_version<'3.5'",
    "oldest-supported-numpy; python_version>='3.5' and python_version<'3.9'",
    "numpy==2.0.2; python_version>='3.9'",
]

build-backend = "setuptools.build_meta"
